### ISSUE TITLE
Remove PDB path from NuGet dll

### ISSUE THREAD

**Issue by xmedeko** [kmcginnes/SpicyTaco.AutoGrid#3]
`SpicyTaco.AutoGrid.dll` contins the PDB path `z:\Projects\SpicyTaco.AutoGrid\src\AutoGrid\obj\Debug\SpicyTaco.AutoGrid.pdb` I have `Z:` mapped as a network drive, sometimes unreacheable. The Visual Studio always hangs for a few seconds trying to look for the PDB path. Please, remove the path form DLL.

I am a newbiew to C# development, but I think the switch `/pdbpath:none` may help?

Also AFAIK you can ship PDB with NuGet, upload it to the [symbolsource](http://www.symbolsource.org) or use [GitLink](https://github.com/GitTools/GitLink).

**Comment by kmcginnes** [comment]
Wow. Thanks for letting me know. It's supposed to be using SymbolSource, but I apparently have something configured wrong. I'll look at it right now.

**Comment by kmcginnes** [comment]
@xmedeko Which version are you using? If you are on 0.9.x then please give 1.0.9 a try. I switched from building and publishing by hand to using AppVeyor. If you are already on 1.0.9 then I'll take another look, but I'm not seeing anything wrong with what I have currently.

**Comment by xmedeko** [comment]
Yeah, I was on 0.9.1, upgrade to the 1.0.9 has fixed the probolem. Thanks.

**Comment by kmcginnes** [comment]
Glad to hear it! I hope I get a chance to spend a little more time on AutoGrid soon. I'd love to implement that feature you suggested.
