### ISSUE TITLE
Publish 1.1.19 into NuGet 

### ISSUE THREAD

**Issue by xmedeko** [kmcginnes/SpicyTaco.AutoGrid#5]
Last version available via NuGet is 1.1.17, see https://www.nuget.org/packages/SpicyTaco.AutoGrid/
Thanks

**Comment by kmcginnes** [comment]
Thank you for the reminder. I need to pull some code out of my "real job" app and put it in here. Should make the MarginBetweenChildren Feature work much better.

**Comment by kmcginnes** [comment]
I've pushed the latest code changes to GitHub, and they are now published to NuGet.org. This code is what I'm using in production apps at work. The StackPanel has gone through fairly rigorous testing so I feel pretty confident that it is stable. And performance has been fine for me, but your mileage may vary.
